workflow changes

diff --git a/.github/workflows/fetch_table.yml b/.github/workflows/fetch_table.yml
--- a/.github/workflows/fetch_table.yml
+++ b/.github/workflows/fetch_table.yml
@@ -44,15 +44,16 @@ jobs:
           
       - name: commit files
         run: |
-          set -e
+          set -e  # Stop execution if a command fails
           git config --local user.email "mattstiles@gmail.com"
           git config --local user.name "stiles"
-          git add -A
-          git commit -m "bot updated data" -a --allow-empty --author="stiles <stiles@users.noreply.github.com>"
-
+          git add -A  # Stage all changes, including deletions
+          git commit -m "bot updated - $(date +'%Y-%m-%d')" -a --allow-empty --author="stiles <stiles@users.noreply.github.com>"
+      
       - name: push changes
         run: |
           set -e  # Stop execution if a command fails
           git push origin main
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        
